# @title Load Packages
import sys
import os


sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# from SpatialAccessibility import calculate_accessibility
import datetime
import os
import copy
import time
import pygame
import random
import numpy as np
import pandas as pd
import seaborn as sns
import geopandas as gpd
import matplotlib.pyplot as plt

import gymnasium as gym
from gymnasium import error, spaces, utils
from gymnasium.spaces import Box, Dict, Discrete, MultiBinary, MultiDiscrete
from gymnasium.spaces import  Tuple, Discrete

from stable_baselines3 import PPO
from stable_baselines3.common.env_checker import check_env
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import DummyVecEnv
from gymnasium.spaces import Discrete
from stable_baselines3.common.callbacks import BaseCallback
from IPython.display import display, HTML


from geopandas import sjoin
from shapely.geometry import Point,box
datasets_path = '../datasets'
print(f'project path is: {datasets_path}\n all data will load from here')
print(f'current date is {datetime.date.today()}')



# @title Libraries: All libraries are loaded here


from datetime import datetime


# import GPUtil



from geopy.distance import geodesic
import logging
import os

# Format date and time
date_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
print(date_time)


from utils.spatialAccessibility import calculate_accessibility_np,test_import,calculate_accessibility_use_np, calculate_gini
from utils.trainingDataLoader import load_training_data
from utils.configLoader import load_config
from utils.configProcessor import setup_environment
# test_import()



import sys

def main(datasets_path,config_path,model_path=None):
    print('*'*66)

    config = load_config(config_path)
    project_path = './'
    # If research_area is not passed, use it from config
    research_area =  config.get('research_area')
    if not research_area:
        raise ValueError("Research area must be defined either in config or as an argument.")
    print(f"Research Area: {research_area}")
    print(f"Datasets Path: {datasets_path}")
    print(f'Config path :{config_path}')
    # datasets_path 一般是 ../datasets/exported_data
    print('*'*66)
    time.sleep(5)
    
    research_area_lower = research_area.lower()
    # 根据研究区域加载数据
    df_od_matrix, df_Origins, df_Destinations = load_training_data(research_area_lower, dataset_dir=datasets_path)
    
    # 将数据添加到配置对象中
    config['df_od_matrix'] = df_od_matrix
    config['df_Origins'] = df_Origins
    config['df_Destinations'] = df_Destinations
    print('rlsolver Print Config')
    print(config)

    action_space, observation_space = setup_environment(config)
    config['action_space'] = action_space
    config['observation_space'] = observation_space
    print("Action Space:", action_space)
    print("Observation Space:", observation_space)

    from envs.env_v3 import HospitalEnvironment_enhanced_v3
    # @title 训练并创建环境实例
    
    env = HospitalEnvironment_enhanced_v3(config)# 创建环境实例
    env = DummyVecEnv([lambda: env])# 包装环境


    # 如果提供了 model_path，则加载模型并跳过训练，否则训练模型
    if model_path:
        print(f"Loading model from {model_path} and skipping training...")
        time.sleep(5)
        from stable_baselines3 import PPO
        model = PPO.load(model_path)  # 加载模型
        

        
    else:
        print('Starting training model based on config file')
        time.sleep(5)
        from trainer.trainer import train_and_save_model
        model = train_and_save_model(env, config, project_path, research_area_lower)  # 训练并保存模型

    # 不管有没有 model path 总是要测试的 
    from trainer.tester import evaluate_model
    mean_reward, std_reward = evaluate_model(model,env)



import argparse
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process some parameters. config file generated by config_maker.ipynb")
    # parser.add_argument('-r', '--research_area', type=str, required=True, help='The research area')
    parser.add_argument('-d', '--datasets_path', type=str, required=True, help='The path to the datasets')
    parser.add_argument('-c', '--config_path', type=str, required=True, help='The path to the configuration file')
    # parser.add_argument('-m', '--mode', type=str, choices=['train_test', 'test'], default='train_test', help='Mode to run: train_test or test')
    parser.add_argument('--model_path', type=str, help='Path to the pre-trained model. If provided, training will be skipped and this model will be used.')
    #  e.g.  python -m rlexperiment.rlsolver -d ./datasets/exported_data -c ./rlexperiment/configs/xiantao/config_xiantao.json --model_path ./rlexperiment/models/xiantao/2021-09-29_15-00-00.zip

    args = parser.parse_args()
    # python rlsolver.py -r xiantao -d ../datasets/exported_data -c ./configs/config_xiantao.json
    # python rlsolver.py --research_area xiantao --datasets_path ../datasets/exported_data --config_path ./configs/config_xiantao.json
    # python -m rlexperiment.rlsolver -r xiantao -d ./datasets/exported_data -c ./rlexperiment/configs/config_xiantao.json
    # (py310) myubuntu@LAPTOP-PCQQF8VV:/mnt/e/workspace/GISense/github/RLSpatialAccess$ python -m rlexperiment.rlsolver -d ./datasets/exported_data -c ./rlexperiment/configs/config_xiantao.json
    main(args.datasets_path, args.config_path,args.model_path)